version: '3.3'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - mongodb:/data/db
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    env_file: ./.env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - $REDIS_PORT:$REDIS_PORT
  node:
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    build: .
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - PORT=$PORT
      - REDIS_PORT=$REDIS_PORT
      - REDIS_HOST=$REDIS_HOST
      - NODE_ENV=$NODE_ENV
    stdin_open: true
    tty: true
volumes:
  mongodb: